WITH CTE AS (
SELECT CAST('2000-01-01' AS Date)	AS Cal_Date
, DATEPART(YEAR, '2000-01-01')		AS Cal_Year
, DATEPART(DAYOFYEAR, '2000-01-01') AS Cal_Year_Day
, DATEPART(QUARTER, '2000-01-01')	AS Cal_Quarter
, DATEPART(MONTH, '2000-01-01')		AS Cal_Month
, DATENAME(MONTH, '2000-01-01')		AS Cal_Month_Name
, DATEPART(DAY, '2000-01-01')		AS Cal_Month_Day
, DATEPART(WEEK, '2000-01-01')		AS Cal_Week
, DATEPART(WEEKDAY, '2000-01-01')	AS Cal_Week_Day
, DATENAME(WEEKDAY, '2000-01-01')	AS Cal_Week_Name


UNION ALL

SELECT DATEADD(DAY,1,Cal_Date)					AS Cal_Date
, DATEPART(YEAR, DATEADD(DAY,1,Cal_Date))		AS Cal_Year
, DATEPART(DAYOFYEAR, DATEADD(DAY,1,Cal_Date))  AS Cal_Year_Day
, DATEPART(QUARTER, DATEADD(DAY,1,Cal_Date))	AS Cal_Quarter
, DATEPART(MONTH, DATEADD(DAY,1,Cal_Date))		AS Cal_Month
, DATENAME(MONTH, DATEADD(DAY,1,Cal_Date))		AS Cal_Month_Name
, DATEPART(DAY, DATEADD(DAY,1,Cal_Date))		AS Cal_Month_Day
, DATEPART(WEEK, DATEADD(DAY,1,Cal_Date))		AS Cal_Week
, DATEPART(WEEKDAY, DATEADD(DAY,1,Cal_Date))	AS Cal_Week_Day
, DATENAME(WEEKDAY, DATEADD(DAY,1,Cal_Date))	AS Cal_Week_Name

FROM CTE
WHERE Cal_Date < CAST('2050-12-31' AS DATE)
)

SELECT ROW_NUMBER() OVER (ORDER BY Cal_Date ASC) AS RN, * INTO CALENDAR
FROM CTE
OPTION (MAXRECURSION 32676)
